### ISSUE TITLE
Source button and playbackRate buttons won't open the dropup menu (only on live environment)

### ISSUE THREAD

**Issue by Bogatinovski** [fluid-player/fluid-player#465]
**Describe the bug**
I have a video player with 3 source files and have also set the `playbackRateEnabled` config property to true. The player is running inside a VueJs app. When running the app on localhost both buttons are working fine. But when I build and deploy the app to the live server, the buttons don't work. Specifically, the dropup menus does not open. The issue is consistently reproducible on Windows Firefox and Chrome and also on Samsung Android Chrome. Strangely, everything is working fine on windows Edge browser!

**To Reproduce**
1. Create the HTML code in the Vue component:
`<video ref="defaultPlayer">
          <source src='https://cdn.fluidplayer.com/videos/valerian-1080p.mkv' data-fluid-hd title="1080p" type='video/mp4'/>
          <source src='https://cdn.fluidplayer.com/videos/valerian-720p.mkv' data-fluid-hd title="720p" type='video/mp4'/>
          <source src='https://cdn.fluidplayer.com/videos/valerian-360p.mkv' title="360p" type='video/mp4'/>
        </video>`
2. Initialize the player: 
`fluidPlayer(this.$refs.defaultPlayer, {
            layoutControls: {
              preload: 'none',
              allowDownload: true,
              playbackRateEnabled: true,
              allowTheatre: false
            },
            hlsjsConfig: {
              xhrSetup: function(xhr) {
                xhr.withCredentials = true
              }
            }
          })`
3. Click on any of the 2 buttons (Sources and PlaybackSpeed icons)
4. Notice that the dropup menu didn't appear with the options to change the setting.

**Expected behavior**
The dropup menu should appear and enable you to select an option to change the setting.

**Screenshots or Links**
I created a [jsfiddle with the same code](https://jsfiddle.net/e1r7ow6a/3/) but unfortunately it is not reproducing the issue.

**Desktop**
 - OS: Windows 10
 - Browser chrome (83.0.4103.61), firefox (77.0.1)

**Smartphone:**
 - Device: Samsung C5 PRO
 - OS: Android 6.0
 - Browser Chrome

**Affected version**
v3.0.0

**Comment by Bogatinovski** [comment]
Here is the actual Live url of the page that is loading the player: [https://hsty.mpp.cloud/about](https://hsty.mpp.cloud/about)
On the following link I have literally copy-pasted the whole Vue component that is loading this video: [https://pastebin.com/RwXUgZH1](https://pastebin.com/RwXUgZH1)

**Comment by Addvilz** [comment]
This is a known "issue" with CSS optimizations performed during build time in Webpack with css-minify. Fluid Player CSS is something that is still pending to be re-done since v2...

As a temporary fix, this CSS will correct the issue. Include it in `style` block right after `@import` for `fluidplayer.css`.

```css
.fluid_video_wrapper.fluid_player_layout_default .fluid_controls_container .fluid_controls_right .fluid_button_subtitles .fluid_subtitles_list,
    .fluid_video_wrapper.fluid_player_layout_default .fluid_controls_container .fluid_controls_right .fluid_button_video_source .fluid_video_sources_list,
    .fluid_video_wrapper.fluid_player_layout_default .fluid_controls_container .fluid_controls_right .fluid_video_playback_rates {
        z-index: 888888 !important;
        opacity: 0.9 !important;
    }
```
